//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedProject
    {
        public int AssignedProjectsID { get; set; }
        public int FK_StaffID { get; set; }
        public int FK_ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
